Graphs for Technician Performance
=================================

```{r knitr, echo=FALSE, warning=FALSE}
library(knitr)
```

```{r setoptions, echo=FALSE, cache=TRUE}
opts_chunk$set(echo = FALSE, results = "hide")
```

```{r computetime, echo=FALSE}
runtime <- format(Sys.time(), "%a %b %d %X %Y")
```
Report run at `r runtime`

Load the libraries
```{r echo= FALSE, results='hide', warning=FALSE, message=FALSE}
library(dplyr)  ##for manipulating the data
library(xlsx) ##for importing and reading excel file into R
library(ggplot2) ##plotting the graphs
library(reshape2) ##for reshaping the datasets
library(gridExtra)
library(ggpubr)##for axis label adjustments
library(xtable) ##for tables to be printed
```

*Read the data*
```{r echo=FALSE}
##read the tech report data
techperf_data <- read.xlsx("Technician Monthly Performance March.xlsx", sheetIndex = 1)

##Read the footprint data
ftdata <- read.csv("ftreportmarch.csv")

```

```{r TableForData, eval=FALSE, echo=FALSE}
knitr::kable(summary(techperf_data))
techtable <- xtable(techperf_data)
print(summary(techtable))
```

*Manipulate the data to create new variables*
```{r echo = FALSE}
###############################################
##MANIPULATING TECHNICIAN REPORT DATA
###############################################
##data for individual techinicians
##indtech_dt: data for individual techs and activities column
indtech_dt <- techperf_data %>% select(O...M.activities, names(techperf_data)[7:19])

##melt the dataset
indtech_mdt <- melt(indtech_dt, id = c("O...M.activities"))
names(indtech_mdt) <- c("Activity.Total", "Technician", "Performance.Score")
##select only totals
techrank <- indtech_mdt %>% filter(Activity.Total == "TOTAL (%)") 

##sumtech_dt to carry summary of the data
sumtech_dt <- techperf_data %>% select(c(1,2,3,6)) %>% 
        filter(!is.na(Scoring)) %>% 
        mutate(Expected.Score = Scoring*100)

##summary performance data
sumperf_dt <- sumtech_dt %>% select(O...M.activities, Expected.Score, Final.Scoring)
names(sumperf_dt) <- c("Activity", "Goal", "Scored")
sumperf_dt$Scored <- round(sumperf_dt$Scored, 1)
sumperf_dt_melt <- melt(sumperf_dt, id.vars = "Activity")

actscore_dt <- techperf_data %>% select(c(1, 7:length(names(techperf_data)))) %>% 
        filter(O...M.activities != "TOTAL (%)") 

###melt the data
actscore_mdt <- melt(actscore_dt, id.vars = "O...M.activities")
###Change names of actscore_mdt
names(actscore_mdt) <- c("Activity", "Technician", "Achievement")

##################################################
#MANIPULATING THE FOOTPRINTS DATA 
##################################################
##select data for only "Allan Kavuma"
allan_ftdt <- ftdata %>% filter(ATC.Regional.Supervisor.Name == "Allan Kavuma")

##Power tickets
power_tts <- allan_ftdt[allan_ftdt$Root.Cause == "Power",]

##Select onlysites with power tickets
site_ptt <- power_tts %>% select(ATC.Site.Name)

##sites that got at least a callout
site1_ptt <- unique(site_ptt$ATC.Site.Name)

##group power tts by site
gpower_tss <- power_tts %>% group_by(ATC.Site.Name) %>% 
        summarise(Total.TTs = n()) %>% 
        arrange(desc(Total.TTs))

##power tts more than 1
rpt_ptts <- gpower_tss %>% filter(Total.TTs > 1)

##DC Faults
dc_tts <- allan_ftdt[allan_ftdt$Root.Cause == "DC Power Faults",]

##Pending faults
Pending_tts <- allan_ftdt[allan_ftdt$Root.Cause == "Pending Faults",]
```


##GRAPHS
```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
############
#Graph: Overall Score Per O&M Activity
############
ggplot(data = sumperf_dt_melt, aes(x = Activity, y = value, fill = variable)) +
        geom_bar(stat = "identity", position = "dodge") + 
        rotate_x_text() +
        labs(title = "Overall Score Per O&M Activity") +
        xlab("O&M Activity") +
        ylab("Percentage (%)") +
        geom_text(aes(y=value, label = value),  
                  color="black", size=3.5)
ggsave("ActivityScore.png", width = 10, height = 5)

############
#Graph: Achievement Status Per O&M Activity
############
###plot the graph
ggplot(data = actscore_mdt, aes(x = Technician, y = Achievement, fill = Activity)) +
        geom_bar(stat = "identity") +
        rotate_x_text() +
        labs(title = "Achievement Status Per O&M Activity") 
ggsave("AchievementStatus.png", width = 10, height = 5)

###########
#Graph: Technician Monthly Performance
###########
ggplot(data = techrank, aes(Technician, Performance.Score)) + 
        geom_col(aes(fill = Performance.Score)) + 
        coord_flip() + 
        labs(title = "Technician Monthly Performance for March") + 
        scale_fill_gradient(low="red", high="green")+
        geom_text(aes(y=Performance.Score, label = Performance.Score), hjust = 1.6)
ggsave("TechPerformance.png", width = 10, height = 5)

#########
#Graph: Total Power Tickets
#########
ggplot(data = power_tts, aes(ATC.Site.Name)) + 
        geom_bar(fill = "salmon1") +
        rotate_x_text()+
        labs(title = "Total Power Tickets")+
        ggsave("TotalPowerTickets.png", width = 10, height = 5)

############
#Graph: Repeat Power Tickets
############
ggplot(data = rpt_ptts, aes(ATC.Site.Name, Total.TTs)) + 
        geom_col(aes(fill = Total.TTs)) +
        rotate_x_text() +
        labs(title = "Repeat Power Tickets")
ggsave("RepeatPowerTickets.png", width = 10, height = 5)

############
#Graph: Pending Fault Per Site
############
##Pending faults
Pending_tts <- allan_ftdt[allan_ftdt$Root.Cause == "Pending Faults",]
ggplot(data = Pending_tts, aes(ATC.Site.Name)) + 
        geom_bar(fill = "firebrick2") +
        rotate_x_text()+
        labs(title = "Pending Faults per site")
ggsave("PendingFaults.png", width = 10, height = 5)

############
#Graph: DC Faults per site
############
##Graph of DC tickets
ggplot(data = dc_tts, aes(ATC.Site.Name)) + 
        geom_bar(fill = "steelblue") +
        rotate_x_text()+
        labs(title = "DC Faults per site")
ggsave("DcFaults.png")

```